### ISSUE TITLE
How about support the footnote with non number markers?

### ISSUE THREAD

**Issue by maxchendt** [LouisBarranqueiro/hexo-footnotes#4]
As in https://jonschlinkert.github.io/remarkable/demo/
> Footnote 1 link[^first].
 Footnote 2 link[^second].
 Inline footnote^[Text of inline footnote] definition.
 Duplicated footnote reference[^second].
 [^first]: Footnote **can have markup**
     and multiple paragraphs.
 [^second]: Footnote text.

**Comment by maxchendt** [comment]
using  meaningful `label` will improve the writing of blog. I think that the JS script can map the label to automatical number.

I would like to ask for another improvement: say, show the content of footnote if the mouse is overhead. For example, the wiki

![screenshot from 2016-09-11 094543](https://cloud.githubusercontent.com/assets/9275768/18414673/0a97b786-7806-11e6-95ea-811b9a704809.png)

**Comment by maxchendt** [comment]
https://github.com/wzpan/hexo-renderer-pandoc , support http://pandoc.org/MANUAL.html#footnotes

**Comment by maxchendt** [comment]
the snippet in https://stackoverflow.com/questions/39564117 works, under hexo-renderer-pandoc

**Comment by LouisBarranqueiro** [comment]
Hey @maxchendt, sorry to respond you late

even if pandoc solves this issue, i'm gonna implement it, because it gonna be great for this plugin which is easiest to use

**Comment by LouisBarranqueiro** [comment]
Just saw that [hexo-renderer-markdown-it](https://github.com/celsomiranda/hexo-renderer-markdown-it) plugin do the job with markdown-it parser and plugins to support extra features like footnote. and you don't have to install something like pandoc. So I recommend you to use this renderer. I'm gonna redirect users to this plugin :)
