### ISSUE TITLE
can brackets be added around the number?

### ISSUE THREAD

**Issue by quentin-chen** [LouisBarranqueiro/hexo-footnotes#6]
if the footnotes can be displayed like:

this is the test[1]

1: footnote for test. ↩

**Comment by LouisBarranqueiro** [comment]
Hey @quentin-chen, you have to edit the code to do that.

**Comment by quentin-chen** [comment]
Ok, I'll take a look at the code, could I ask you for help if I met problems?

**Comment by quentin-chen** [comment]
New plugin now supporting the feature:
https://github.com/quentin-chen/hexo-reference

If you no longer maintain this plugin, you can redirect visitors to my new plugin. I will keep on enhancing the footnote, cuz I don't want to use other renderers like `hexo-renderer-markdown-it`.  They don't support a lot of themes using jade or something else.
